c1 = input('digite algo:')
print('o tipo primitivo é ', type(c1))
print('so tem espaços',c1.isspace())
print('é um numero', c1.isnumeric())
print('é alfabetico', c1.isalpha())
print('e alfanumerico', c1.isalnum())
print('esta em maiuscula', c1.isupper())
print('esta em minusculas', c1.islower())
print('esta capitalizado', c1.title())