num = int(input('digite um numero para ver a tabuada'))
print('======================')
print('{} * {} = {}'.format(1, num, 1*num))
print('{} * {} = {}'.format(2, num, 2*num))
print('{} * {} = {}'.format(3, num, 3*num))
print('{} * {} = {}'.format(4, num, 4*num))
print('{} * {} = {}'.format(5, num, 5*num))
print('{} * {} = {}'.format(6, num, 6*num))
print('{} * {} = {}'.format(7, num, 7*num))
print('{} * {} = {}'.format(8, num, 8*num))
print("{} * {} = {}".format(9, num, 9*num))
print("{} * {} = {}".format(10, num, 10*num))
print('=======================')