al = input('digite algo:')
print('o tipo primitivo é :',type(al))
print('so tem espaços: ',al.isspace())
print('é um numero: ',al.isnumeric())
print('é alfabetico: ',al.isalpha())
print('é alfanumerico: ',al.isalnum())
print('esta em maiúsculas: ',al.islower())
print('esta em minusculas: ',al.isupper())
print('esta capitalizada',al.istitle())