nm = int(input('digite um numero: '))
print('======================')
print('{} + {} = {}'.format(nm, 1, nm+1))
print('{} + {} = {}'.format(nm, 2, nm+2))
print('{} + {} = {}'.format(nm, 3, nm+3))
print('{} + {} = {}'.format(nm, 4, nm+4))
print('{} + {} = {}'.format(nm, 5, nm+5))
print('{} + {} = {}'.format(nm, 6, nm+6))
print('{} + {} = {}'.format(nm, 7, nm+7))
print('{} + {} = {}'.format(nm, 8, nm+8))
print('{} + {} = {}'.format(nm, 9, nm+9))
print('{} + {} = {}'.format(nm, 10, nm+10))
print('=======================')